name: Run surveyjoin tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test-r:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.3.1"

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("remotes"))'

      - name: Install surveyjoin
        run: |
          Rscript -e 'remotes::install_github("DFO-NOAA-Pacific/surveyjoin")'

      - name: Run testthat tests
        run: |
          Rscript -e 'testthat::test_dir("tests")'

      - name: Check SQLite database file
        run: |
          if [ ! -f "$(Rscript -e 'cat(sql_folder())')" ]; then
            echo "SQLite database was not created!"
            exit 1
          fi
